version: '3.1'

services:

  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=dictionary

  mongodb:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dictionary

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    ports:
      - 15673:15672
      - 5674:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
